language: node_js
node_js:
  - '14'

notifications:
  email: false

before_script:
  - git clone --branch v6.5.0 --single-branch --depth 1 https://github.com/openlayers/openlayers

script:
  - yarn prepare-npm
  - yarn prepare-dt
