name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js LTS
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - uses: actions/checkout@v2
        with:
          repository: 'openlayers/openlayers'
      - run: yarn --frozen-lockfile
      - run: yarn run prepare-npm
      - run: yarn run prepare-dt
